#!/bin/bash

if [ ! -d build ]; then
    mkdir build
fi

cd translator
source .venv/bin/activate
python main.py "../$1" "../build/out.c"
deactivate
cd ..

cp -R runtime/. build

cd build
cmake .
cmake --build .
./out
