#!/bin/bash

if [ ! -d translator/.venv ]; then
    cd translator/
    uv venv
    source .venv/bin/activate
    antlr4 -Dlanguage=Python3 -visitor Lisp.g4
    uv sync
    deactivate
fi

if [ ! -d build ]; then
    mkdir build
fi

cd translator
source .venv/bin/activate
python src/main.py "../$1" -o "../build/out.c"
deactivate
cd ..

cp runtime/runtime.h runtime/runtime.c build 

cd build
gcc out.c runtime.c -o out
./out
