#!/bin/bash

if [ ! -d translator/.venv ]; then
    cd translator/
    uv venv
    source .venv/bin/activate
    uv sync
    antlr4 -Dlanguage=Python3 -visitor Lisp.g4 -o src
    deactivate
    cd ..
fi

if [ ! -d build ]; then
    mkdir build
fi

if [ -f build/out ]; then
    rm build/out
fi

cd translator
source .venv/bin/activate
python src/main.py "../$1" -o "../build/out.c"
deactivate
cd ..

cp runtime/runtime.h runtime/runtime.c build 

cd build
gcc out.c runtime.c -o out
./out
