#pragma once

#include "lib/core.h"
#include "lib/arithmetic.h"
#include "lib/io.h"
#include "lib/objects/primitive.h"
#include "lib/objects/evaluable.h"
#include "lib/logic.h"
#include "lib/comparation.h"
#include "lib/environment.h"
#include "lib/objects/vector.h"
#include "lib/objects/lambda.h"
#include "lib/native_calls.h"
#include "lib/objects/pair.h"
#include "lib/objects/list.h"
