#pragma once

#include "lib/core/core.h"
#include "lib/core/arithmetic.h"
#include "lib/core/io.h"
#include "lib/objects/primitive.h"
#include "lib/objects/evaluable.h"
#include "lib/core/logic.h"
#include "lib/core/comparation.h"
#include "lib/core/environment.h"
#include "lib/objects/vector.h"
#include "lib/objects/lambda.h"
#include "lib/core/native_calls.h"
#include "lib/objects/pair.h"
#include "lib/objects/list.h"
