(+ 2 3)
(define x 1)
(+ x 5)
(display (set! x 1))
(+ x 5)
(define y "hello")
(+ y x)
(display (let ()
           (display x)
           (display y)
           (display (set! y 9))
           (+ x y)))
(+ 1 2 3 4 5 6 7)
(display (let ((a 1) (b 2))
           (+ a b x y)
           (set! a 10)
           (set! x 5)
           (+ a b x y)))
(display (let ((u 1))
           (display (let ((v u))
                      (set! u 5)
                      (set! v 90)
                      (+ u v)))))
